/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jums_store;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MALILONG_CpE121
 */
public class jums_jframe extends javax.swing.JFrame {

    DefaultTableModel model;
    
    String barcode;
    String menu;
    String price;
    String quantity;

    /**
     * Creates new form jums_jframe
     */
    public jums_jframe() {
        initComponents();
         initComponents();
        model=(DefaultTableModel)pastrytable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        MENU1 = new javax.swing.JLabel();
        MENU2 = new javax.swing.JLabel();
        MENU3 = new javax.swing.JLabel();
        MENU4 = new javax.swing.JLabel();
        MENU5 = new javax.swing.JLabel();
        MENU6 = new javax.swing.JLabel();
        MENU7 = new javax.swing.JLabel();
        MENU8 = new javax.swing.JLabel();
        newmenu = new javax.swing.JLabel();
        MENU9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        newprice = new javax.swing.JLabel();
        PRICE1 = new javax.swing.JLabel();
        PRICE2 = new javax.swing.JLabel();
        PRICE3 = new javax.swing.JLabel();
        PRICE4 = new javax.swing.JLabel();
        PRICE5 = new javax.swing.JLabel();
        PRICE6 = new javax.swing.JLabel();
        PRICE7 = new javax.swing.JLabel();
        PRICE8 = new javax.swing.JLabel();
        PRICE9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BUTTON1 = new javax.swing.JButton();
        BUTTON2 = new javax.swing.JButton();
        BUTTON3 = new javax.swing.JButton();
        BUTTON4 = new javax.swing.JButton();
        BUTTON5 = new javax.swing.JButton();
        BUTTON6 = new javax.swing.JButton();
        BUTTON7 = new javax.swing.JButton();
        BUTTON8 = new javax.swing.JButton();
        BUTTON9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pastrytable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        quantitytextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 102, 0));
        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("    JUMS PASTRIES");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 153), new java.awt.Color(204, 102, 0), new java.awt.Color(255, 204, 153)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 290, 70));

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MENU1.setText("Croissant");

        MENU2.setText("Cheesecake");

        MENU3.setText("Macaron");

        MENU4.setText("Crepe");

        MENU5.setText("Pretzel");

        MENU6.setText("Doughnut");

        MENU7.setText("Cupcake");

        MENU8.setText("Brownie");

        newmenu.setBackground(new java.awt.Color(153, 153, 255));
        newmenu.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        newmenu.setForeground(new java.awt.Color(102, 51, 0));
        newmenu.setText("MENU");

        MENU9.setText("Tart");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(newmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(MENU6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MENU4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(MENU5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(MENU3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MENU8)
                                    .addComponent(MENU7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MENU9)))
                            .addComponent(MENU2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MENU1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MENU1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MENU2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MENU3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MENU4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MENU5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MENU6)
                .addGap(12, 12, 12)
                .addComponent(MENU7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MENU8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MENU9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        newprice.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        newprice.setForeground(new java.awt.Color(102, 51, 0));
        newprice.setText("PRICE");

        PRICE1.setText("$ 50");

        PRICE2.setText("$ 70");

        PRICE3.setText("$ 25");

        PRICE4.setText("$ 30");

        PRICE5.setText("$ 22");

        PRICE6.setText("$ 10");

        PRICE7.setText("$15");

        PRICE8.setText("$ 50");

        PRICE9.setText("$ 75");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newprice)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PRICE2)
                            .addComponent(PRICE1)
                            .addComponent(PRICE3)
                            .addComponent(PRICE4)
                            .addComponent(PRICE5)
                            .addComponent(PRICE9)
                            .addComponent(PRICE8)
                            .addComponent(PRICE7)
                            .addComponent(PRICE6))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newprice, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PRICE1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PRICE2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PRICE3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PRICE4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PRICE5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PRICE6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PRICE7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PRICE8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PRICE9)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 204, 102));
        jLabel2.setFont(new java.awt.Font("Ravie", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("BARCODE");

        BUTTON1.setText("1");
        BUTTON1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON1ActionPerformed(evt);
            }
        });

        BUTTON2.setText("2");
        BUTTON2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON2ActionPerformed(evt);
            }
        });

        BUTTON3.setText("3");
        BUTTON3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON3ActionPerformed(evt);
            }
        });

        BUTTON4.setText("4");
        BUTTON4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON4ActionPerformed(evt);
            }
        });

        BUTTON5.setText("5");
        BUTTON5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON5ActionPerformed(evt);
            }
        });

        BUTTON6.setText("6");
        BUTTON6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON6ActionPerformed(evt);
            }
        });

        BUTTON7.setText("7");
        BUTTON7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON7ActionPerformed(evt);
            }
        });

        BUTTON8.setText("8");
        BUTTON8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON8ActionPerformed(evt);
            }
        });

        BUTTON9.setText("9");
        BUTTON9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUTTON1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTON1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTON2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTON3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTON4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTON5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTON6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTON7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTON8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUTTON9)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 320, 280));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        pastrytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Menu", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(pastrytable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 310, 400));

        jLabel23.setText("quantity");

        quantitytextfield.setText("1");
        quantitytextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitytextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quantitytextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantitytextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON1ActionPerformed
        // TODO add your handling code here:
        String quantiti=quantitytextfield.getText();
        double total=0;
        int quantnumber=Integer.parseInt(quantiti);
        if (quantnumber>=1){
            menu=MENU1.getText();
            barcode="1";
            price=PRICE1.getText();
            quantity=quantitytextfield.getText();
            
            model.addRow(new Object[]{menu,barcode,price,quantity});
            quantitytextfield.setText("1");
        }else{
            JOptionPane.showMessageDialog(null, "INVALID QUANTITY");
            quantitytextfield.setText("1");
        }
     
    }//GEN-LAST:event_BUTTON1ActionPerformed

    private void BUTTON2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON2ActionPerformed
       String quantiti=quantitytextfield.getText();
       double total=0;
        int quantnumber=Integer.parseInt(quantiti);
        if (quantnumber>=1){
            menu=MENU2.getText();
            barcode="2";
            price=PRICE2.getText();
            quantity=quantitytextfield.getText();
            
            model.addRow(new Object[]{menu,barcode,price,quantity});
            quantitytextfield.setText("1");
        }else{
            JOptionPane.showMessageDialog(null, "INVALID QUANTITY");
            quantitytextfield.setText("1");
        }
    }//GEN-LAST:event_BUTTON2ActionPerformed

    private void BUTTON3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON3ActionPerformed
        // TODO add your handling code here:
        String quantiti=quantitytextfield.getText();
       double total=0;
        int quantnumber=Integer.parseInt(quantiti);
        if (quantnumber>=1){
            menu=MENU3.getText();
            barcode="3";
            price=PRICE3.getText();
            quantity=quantitytextfield.getText();
            
            model.addRow(new Object[]{menu,barcode,price,quantity});
            quantitytextfield.setText("1");
        }else{
            JOptionPane.showMessageDialog(null, "INVALID QUANTITY");
            quantitytextfield.setText("1");
        }
      
    }//GEN-LAST:event_BUTTON3ActionPerformed

    private void BUTTON4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON4ActionPerformed
        // TODO add your handling code here:
       String quantiti=quantitytextfield.getText();
       double total=0;
       int quantnumber=Integer.parseInt(quantiti);
       if (quantnumber>=1){
           menu=MENU4.getText();
           barcode="4";
           price=PRICE4.getText();
            quantity=quantitytextfield.getText();
            
            model.addRow(new Object[]{menu,barcode,price,quantity});
            quantitytextfield.setText("1");
        }else{
            JOptionPane.showMessageDialog(null, "INVALID QUANTITY");
            quantitytextfield.setText("1");
       }
    }//GEN-LAST:event_BUTTON4ActionPerformed

    private void BUTTON5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON5ActionPerformed
        // TODO add your handling code here:
        String quantiti=quantitytextfield.getText();
        double total=0;
        int quantnumber=Integer.parseInt(quantiti);
        if (quantnumber>=1){
            menu=MENU5.getText();
            barcode="5";
            price=PRICE5.getText();
            quantity=quantitytextfield.getText();
            
            model.addRow(new Object[]{menu,barcode,price,quantity});
            quantitytextfield.setText("1");
        }else{
            JOptionPane.showMessageDialog(null, "INVALID QUANTITY");
            quantitytextfield.setText("1");
        }
        
    }//GEN-LAST:event_BUTTON5ActionPerformed

    private void BUTTON6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON6ActionPerformed
        // TODO add your handling code here:
        String quantiti=quantitytextfield.getText();
        double total=0;
        int quantnumber=Integer.parseInt(quantiti);
        if(quantnumber>=1){
            menu=MENU6.getText();
            barcode="6";
            price=PRICE6.getText();
            quantity=quantitytextfield.getText();
            
            model.addRow(new Object[]{menu,barcode,price,quantity});
            quantitytextfield.setText("1");
        }else{
            JOptionPane.showMessageDialog(null, "INVALID QUANTITY");
            quantitytextfield.setText("1");
        }
    }//GEN-LAST:event_BUTTON6ActionPerformed

    private void BUTTON7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON7ActionPerformed
        // TODO add your handling code here:
        String quantiti=quantitytextfield.getText();
        double total=0;
        int quantnumber=Integer.parseInt(quantiti);
        if(quantnumber>=1){
            menu=MENU7.getText();
            barcode="7";
            price=PRICE7.getText();
            quantity=quantitytextfield.getText();
            
            model.addRow(new Object[]{menu,barcode,price,quantity});
            quantitytextfield.setText("1");
        }else{
            JOptionPane.showMessageDialog(null, "INVALID QUANTITY");
            quantitytextfield.setText("1");
        }
       
    }//GEN-LAST:event_BUTTON7ActionPerformed

    private void BUTTON8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON8ActionPerformed
        // TODO add your handling code here:String quantity=quantitybutton.getText();
      String quantiti=quantitytextfield.getText();
        double total=0;
        int quantnumber=Integer.parseInt(quantiti);
        if(quantnumber>=1){
            menu=MENU8.getText();
            barcode="8";
            price=PRICE8.getText();
            quantity=quantitytextfield.getText();
            
            model.addRow(new Object[]{menu,barcode,price,quantity});
            quantitytextfield.setText("1");
        }else{
            JOptionPane.showMessageDialog(null, "INVALID QUANTITY");
            quantitytextfield.setText("1");
        }
    }//GEN-LAST:event_BUTTON8ActionPerformed

    private void BUTTON9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON9ActionPerformed
        // TODO add your handling code here:
        String quantiti=quantitytextfield.getText();
        double total=0;
        int quantnumber=Integer.parseInt(quantiti);
        if(quantnumber>=1){
            menu=MENU9.getText();
            barcode="9";
            price=PRICE9.getText();
            quantity=quantitytextfield.getText();
            
            model.addRow(new Object[]{menu,barcode,price,quantity});
            quantitytextfield.setText("1");
        }else{
            JOptionPane.showMessageDialog(null, "INVALID QUANTITY");
            quantitytextfield.setText("1");
        }
    }//GEN-LAST:event_BUTTON9ActionPerformed

    private void quantitytextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitytextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitytextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jums_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jums_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jums_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jums_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jums_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTON1;
    private javax.swing.JButton BUTTON2;
    private javax.swing.JButton BUTTON3;
    private javax.swing.JButton BUTTON4;
    private javax.swing.JButton BUTTON5;
    private javax.swing.JButton BUTTON6;
    private javax.swing.JButton BUTTON7;
    private javax.swing.JButton BUTTON8;
    private javax.swing.JButton BUTTON9;
    private javax.swing.JLabel MENU1;
    private javax.swing.JLabel MENU2;
    private javax.swing.JLabel MENU3;
    private javax.swing.JLabel MENU4;
    private javax.swing.JLabel MENU5;
    private javax.swing.JLabel MENU6;
    private javax.swing.JLabel MENU7;
    private javax.swing.JLabel MENU8;
    private javax.swing.JLabel MENU9;
    private javax.swing.JLabel PRICE1;
    private javax.swing.JLabel PRICE2;
    private javax.swing.JLabel PRICE3;
    private javax.swing.JLabel PRICE4;
    private javax.swing.JLabel PRICE5;
    private javax.swing.JLabel PRICE6;
    private javax.swing.JLabel PRICE7;
    private javax.swing.JLabel PRICE8;
    private javax.swing.JLabel PRICE9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newmenu;
    private javax.swing.JLabel newprice;
    private javax.swing.JTable pastrytable;
    private javax.swing.JTextField quantitytextfield;
    // End of variables declaration//GEN-END:variables
}
